spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:5}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
        
  exposed:
    show-sql: false
    
  jooq:
    sql-dialect: MYSQL
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
        
logging:
  level:
    com.mylifeisrpg: INFO
    org.springframework: WARN
    org.jetbrains.exposed: WARN
    com.zaxxer.hikari: WARN