spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
        
  exposed:
    show-sql: true
    
  jooq:
    sql-dialect: H2
    
logging:
  level:
    com.mylifeisrpg: DEBUG