spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myliftisrpg_dev
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    
  exposed:
    show-sql: true
    
  jooq:
    sql-dialect: MYSQL
    
logging:
  level:
    com.mylifeisrpg: DEBUG
    org.springframework.web: DEBUG
    org.jetbrains.exposed: DEBUG
    com.zaxxer.hikari: INFO